version: '2'

services:
    applications:
        container_name: symfony_applications
        image: tianon/true
        volumes: 
            - ../:/var/www

    workspace:
        container_name: symfony_workspace
        build:
            context: ./workspace
            args:
                - PUID=1000
                - PGID=1000
                - TIMEZONE=America/Sao_Paulo
        volumes_from:
            - applications
        extra_hosts:
            - "dockerhost:10.0.75.1"
        ports:
            - "2222:22"
        tty: true
